### ISSUE TITLE
Fall Detector

### ISSUE THREAD

**Issue by IzzySoft** [altermarkive/altermarkive#1]
Unfortunately, you forgot to enable the issue tracker there – so I have to ask you here, as I couldn't find any other means to contact you…

Just a minor thing: can you please take care to increment `versionCode` with each release? According to the `build.gradle` that should be done automatically (using the number of commits) – but the latest release (from 2 days ago) still shows up with `versionCode:1`. As Android uses this field to tell versions apart, it won't recognize v0.2.0 as update to the previous version.

Thanks in advance!

**Comment by altermarkive** [comment]
Hi @IzzySoft !

Happy to see interest in my humble app from the F-Droid community!
Well, it's not quite an oversight that the repo doesn't have an issue tracker :)
I don't actively maintain it - but having (temporarily) an access to an Android device I decided it would be fun to learn Kotlin and porting my 7 year old code provided me with a robust context for it.
Anyhow, I do appreciate your feedback and the issue should now be fixed.

Thank you and have a nice day!

**Comment by IzzySoft** [comment]
Thanks for your swift reaction, @altermarkive! Looks like I'm no unknown actor anymore that I'm automatically associated with the F-Droid community :smile: Indeed I've added *Fall Detector* [to my repo](https://apt.izzysoft.de/fdroid/index/apk/altermarkive.guardian) recently (in case you want to link there, I can offer you [this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it)) – and with today's update I can now confirm the issue solved.

As you write you're not actively maintaining the app, consider this a note3 for the future: should you wish to have your app brought to F-Droid.org's own repo, we'll gladly help you get it listed there. From what my scanners report, it looks promising to meet the requirements there.

All the best for you!

**Comment by altermarkive** [comment]
Hi @IzzySoft - I'll consider listing the app on the main F-Droid.org repo, thank you for the offer!

As for the badge - I suppose that all I need to do is link it like this (I haven't used F-Droid repositories so please pardon my question), right? 

[<img alt="IzzyOnDroid" src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" width="200px"/>](https://apt.izzysoft.de/fdroid/index/apk/altermarkive.guardian)

**Comment by IzzySoft** [comment]
> I'll consider listing the app on the main F-Droid.org repo, thank you for the offer!

Gladly! Just let me know when you need help with that. If you open your [Request For Packaging](https://gitlab.com/fdroid/rfp/-/issues) we'll probably meet there as I'm one of the F-Droid maintainers :smiley:

> I suppose that all I need to do is link it like this

Yes, that would be nice! If you have that in your Readme, people can find their way from the listing there to the index (linked from the bottom of that page) easily, where they see instructions on how to add the repo to their F-Droid client if they wish. From that point on, they'd automatically receive any updates you'll publish :smiley:
